# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/richard/code/jarvis/software/blinky/blinky.srcs/sources_1/bd/blinky/ip/blinky_processing_system7_0_0/blinky_processing_system7_0_0.xci
# IP: The module: 'blinky_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/richard/code/jarvis/software/blinky/blinky.gen/sources_1/bd/blinky/ip/blinky_processing_system7_0_0/blinky_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'blinky_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/richard/code/jarvis/software/blinky/blinky.srcs/sources_1/bd/blinky/ip/blinky_processing_system7_0_0/blinky_processing_system7_0_0.xci
# IP: The module: 'blinky_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/richard/code/jarvis/software/blinky/blinky.gen/sources_1/bd/blinky/ip/blinky_processing_system7_0_0/blinky_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'blinky_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
