# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Zybo-Master.xdc

# Block Designs: bd/blinky/blinky.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blinky || ORIG_REF_NAME==blinky} -quiet] -quiet

# IP: bd/blinky/ip/blinky_processing_system7_0_0/blinky_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blinky_processing_system7_0_0 || ORIG_REF_NAME==blinky_processing_system7_0_0} -quiet] -quiet

# IP: bd/blinky/ip/blinky_axi_gpio_0_0/blinky_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blinky_axi_gpio_0_0 || ORIG_REF_NAME==blinky_axi_gpio_0_0} -quiet] -quiet

# IP: bd/blinky/ip/blinky_axi_smc_0/blinky_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blinky_axi_smc_0 || ORIG_REF_NAME==blinky_axi_smc_0} -quiet] -quiet

# IP: bd/blinky/ip/blinky_rst_ps7_0_50M_0/blinky_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blinky_rst_ps7_0_50M_0 || ORIG_REF_NAME==blinky_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: /home/richard/code/jarvis/software/blinky/blinky.gen/sources_1/bd/blinky/blinky_ooc.xdc
