domain_path: /home/drew/Documents/github/jarvis/software/blinky/platform/export/platform/sw/standalone_ps7_cortexa9_0
app_src_dir: /home/drew/embedded/xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
