domain_path: /home/richard/code/jarvis/software/blinky/blink2/export/blink2/sw/standalone_ps7_cortexa9_0
app_src_dir: /home/richard/embedded/Vitis/2024.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
