# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/main/main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main || ORIG_REF_NAME==main} -quiet] -quiet

# IP: bd/main/ip/main_processing_system7_0_1/main_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_processing_system7_0_1 || ORIG_REF_NAME==main_processing_system7_0_1} -quiet] -quiet

# XDC: /home/richard/code/jarvis/software/jarvis-software/jarvis-software.gen/sources_1/bd/main/main_ooc.xdc
