# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/richard/code/jarvis/software/jarvis-software/jarvis-software.srcs/sources_1/bd/main/ip/main_processing_system7_0_1/main_processing_system7_0_1.xci
# IP: The module: 'main_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/richard/code/jarvis/software/jarvis-software/jarvis-software.gen/sources_1/bd/main/ip/main_processing_system7_0_1/main_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/richard/code/jarvis/software/jarvis-software/jarvis-software.srcs/sources_1/bd/main/ip/main_processing_system7_0_1/main_processing_system7_0_1.xci
# IP: The module: 'main_processing_system7_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/richard/code/jarvis/software/jarvis-software/jarvis-software.gen/sources_1/bd/main/ip/main_processing_system7_0_1/main_processing_system7_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_processing_system7_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
